//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduvetKonovalov.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Courses
    {
        public int IdCourses { get; set; }
        public string NameCourses { get; set; }
        public decimal PriceCourses { get; set; }
        public int IdTypeCourses { get; set; }
        public string AddressCourses { get; set; }
        public string ShortDescriptionCourses { get; set; }
        public byte[] PhotoCourse { get; set; }
        public int IdStaff { get; set; }
    
        public virtual Staff Staff { get; set; }
        public virtual TypeCourses TypeCourses { get; set; }
    }
}
