//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduvetKonovalov.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public Login()
        {
            this.Staff = new HashSet<Staff>();
            this.User = new HashSet<User>();
        }
    
        public int IdLogin { get; set; }
        public string LoginUser { get; set; }
    
        public virtual ICollection<Staff> Staff { get; set; }
        public virtual ICollection<User> User { get; set; }
    }
}
