//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduvetKonovalov.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provider
    {
        public Provider()
        {
            this.VeterinaryEquipment = new HashSet<VeterinaryEquipment>();
        }
    
        public int IdProvider { get; set; }
        public string NameProvider { get; set; }
        public string NumberPhoneProvider { get; set; }
        public string EmailProvider { get; set; }
    
        public virtual ICollection<VeterinaryEquipment> VeterinaryEquipment { get; set; }
    }
}
