//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduvetKonovalov.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestComing
    {
        public RequestComing()
        {
            this.RequestVeterinaryEquipment = new HashSet<RequestVeterinaryEquipment>();
        }
    
        public int IdRequestComing { get; set; }
        public int AmountComing { get; set; }
        public decimal SumComing { get; set; }
    
        public virtual ICollection<RequestVeterinaryEquipment> RequestVeterinaryEquipment { get; set; }
    }
}
