//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduvetKonovalov.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestRemainder
    {
        public RequestRemainder()
        {
            this.RequestVeterinaryEquipment = new HashSet<RequestVeterinaryEquipment>();
        }
    
        public int IdRequestRemainder { get; set; }
        public int AmountRemainder { get; set; }
        public decimal SumRemainder { get; set; }
    
        public virtual ICollection<RequestVeterinaryEquipment> RequestVeterinaryEquipment { get; set; }
    }
}
