//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduvetKonovalov.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int IdStaff { get; set; }
        public string LastNameStaff { get; set; }
        public string FirstNameStaff { get; set; }
        public string MiddleNameStaff { get; set; }
        public string NumberPhoneStaff { get; set; }
        public System.DateTime DateOfBirthStaff { get; set; }
        public int IdPassport { get; set; }
        public int IdGender { get; set; }
        public int IdLogin { get; set; }
        public int IdPassword { get; set; }
        public byte[] PhotoStaff { get; set; }
        public string AdressStaff { get; set; }
        public string FullName { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual Login Login { get; set; }
        public virtual Passport Passport { get; set; }
        public virtual Password Password { get; set; }
    }
}
