//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduvetKonovalov.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public Staff()
        {
            this.Courses = new HashSet<Courses>();
            this.VeterinaryEquipment = new HashSet<VeterinaryEquipment>();
        }
    
        public int IdStaff { get; set; }
        public string LastNameStaff { get; set; }
        public string FirstNameStaff { get; set; }
        public string MiddleNameStaff { get; set; }
        public string NumberPhoneStaff { get; set; }
        public System.DateTime DateOfBirthStaff { get; set; }
        public int IdPassport { get; set; }
        public int IdGender { get; set; }
        public byte[] PhotoStaff { get; set; }
        public string AdressStaff { get; set; }
        public string FullName { get; set; }
        public int IdJobTitle { get; set; }
        public Nullable<int> IdUser { get; set; }
    
        public virtual ICollection<Courses> Courses { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual JobTitle JobTitle { get; set; }
        public virtual Passport Passport { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<VeterinaryEquipment> VeterinaryEquipment { get; set; }
    }
}
