//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduvetKonovalov.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeCourses
    {
        public TypeCourses()
        {
            this.Courses = new HashSet<Courses>();
        }
    
        public int IdTypeCourses { get; set; }
        public string NameTypeCourses { get; set; }
    
        public virtual ICollection<Courses> Courses { get; set; }
    }
}
