//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduvetKonovalov.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int IdUser { get; set; }
        public int IdLogin { get; set; }
        public int IdPassword { get; set; }
        public int IdRole { get; set; }
    
        public virtual Login Login { get; set; }
        public virtual Password Password { get; set; }
        public virtual Role Role { get; set; }
    }
}
