//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EduvetKonovalov.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class VeterinaryEquipment
    {
        public int IdVeterinaryEquipment { get; set; }
        public string NameVeterinaryEquipment { get; set; }
        public int IdTypeVeterinaryEquipment { get; set; }
        public System.DateTime RecordingDate { get; set; }
        public string WhereDidItComeFrom { get; set; }
        public int IdStaff { get; set; }
        public int IdComing { get; set; }
        public int IdConsumption { get; set; }
        public int IdRemainder { get; set; }
        public byte[] PhotoVeterinaryEquipment { get; set; }
    
        public virtual Coming Coming { get; set; }
        public virtual Consumption Consumption { get; set; }
        public virtual Remainder Remainder { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual TypeVeterinaryEquipment TypeVeterinaryEquipment { get; set; }
    }
}
